# Generated by Django 4.1.2 on 2022-10-31 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField(null=True)),
                ("number_of_times", models.IntegerField(null=True)),
                ("situation_emotion", models.CharField(max_length=1000, null=True)),
                ("afterwards_feeling", models.CharField(max_length=1000, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Journal",
                "ordering": ["-ocurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("thought", models.CharField(max_length=1000, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="web.journal"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Thoughts",
                "ordering": ["-created_at"],
            },
        ),
    ]
