# Generated by Django 4.1.3 on 2022-11-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.CharField(max_length=280, null=True)),
                ("general", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="thought",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="journal",
            name="afterwards_feeling",
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="situation_emotion",
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name="thought",
            name="thought",
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response", models.CharField(max_length=280, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("M", "Mental"), ("E", "Emotional"), ("P", "Physical")], default="E", max_length=1
                    ),
                ),
                ("general", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reward", models.CharField(max_length=280, null=True)),
                ("general", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocurred_at", models.DateTimeField(null=True)),
                ("number_of_times", models.IntegerField(null=True)),
                ("cue", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.cue")),
                (
                    "reward",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.reward"),
                ),
                (
                    "routine",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.routine"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
